import jsPDF from 'jspdf'
import { formatTime12, formatDate, today, daysAgo } from './dateUtils'

const COLORS = {
  primary: [232, 108, 80],
  text: [44, 36, 32],
  muted: [107, 94, 84],
  light: [168, 152, 136],
  border: [236, 232, 225],
  green: [52, 166, 108],
  red: [217, 68, 82],
  white: [255, 255, 255],
  bg: [250, 248, 245],
}

const CAT_COLORS = {
  heart: [217, 68, 82],
  diuretic: [74, 143, 212],
  stomach: [139, 108, 193],
  blood: [212, 147, 10],
  other: [168, 152, 136],
}

function addHeader(doc, title, childName) {
  doc.setFillColor(...COLORS.primary)
  doc.rect(0, 0, 210, 32, 'F')
  doc.setTextColor(...COLORS.white)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 14, 16)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(childName, 14, 26)
  const dateStr = new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })
  doc.text(dateStr, 196, 26, { align: 'right' })
  doc.setTextColor(...COLORS.text)
}

function addFooter(doc, page) {
  doc.setFontSize(7)
  doc.setTextColor(...COLORS.light)
  doc.text('Generated by Little Legend Tracker', 14, 287)
  doc.text(`Page ${page}`, 196, 287, { align: 'right' })
}

export function generateMedSchedule(medications, childName) {
  const doc = new jsPDF()
  addHeader(doc, 'Medication Schedule', childName)

  let y = 42

  // Title
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('Daily Medication Schedule', 14, y)
  y += 10

  // Build time slots
  const slots = {}
  medications.forEach(med => {
    med.times.forEach(t => {
      if (!slots[t]) slots[t] = []
      slots[t].push(med)
    })
  })
  const sortedTimes = Object.keys(slots).sort()

  // Table header
  doc.setFillColor(...COLORS.bg)
  doc.rect(14, y, 182, 8, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.muted)
  doc.text('TIME', 16, y + 6)
  doc.text('MEDICATION', 48, y + 6)
  doc.text('DOSE', 110, y + 6)
  doc.text('CATEGORY', 142, y + 6)
  doc.text('INSTRUCTIONS', 170, y + 6)
  y += 12

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)

  sortedTimes.forEach(time => {
    slots[time].forEach((med, i) => {
      if (y > 270) {
        addFooter(doc, doc.internal.getNumberOfPages())
        doc.addPage()
        y = 20
      }

      // Category color dot
      const catColor = CAT_COLORS[med.category] || CAT_COLORS.other
      doc.setFillColor(...catColor)
      doc.circle(18, y - 1, 2, 'F')

      doc.setTextColor(...COLORS.text)
      doc.setFont('helvetica', 'bold')
      doc.text(formatTime12(time) || '', 24, y)
      doc.setFont('helvetica', 'normal')
      doc.text(med.name || '', 48, y)
      doc.text(med.dose || '', 110, y)
      doc.setTextColor(...catColor)
      doc.text(med.category || '', 142, y)
      doc.setTextColor(...COLORS.muted)
      doc.text((med.instructions || '').substring(0, 20), 170, y)
      y += 8

      // Separator line
      doc.setDrawColor(...COLORS.border)
      doc.line(14, y - 3, 196, y - 3)
    })
  })

  // Summary
  y += 6
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text(`Total: ${medications.length} medications, ${sortedTimes.length} time slots per day`, 14, y)

  addFooter(doc, 1)
  doc.save(`med-schedule-${childName.toLowerCase().replace(/\s+/g, '-')}.pdf`)
}

export function generateDailySummary(data, childName, date) {
  const d = date || today()
  const doc = new jsPDF()
  addHeader(doc, 'Daily Summary', `${childName} - ${formatDate(d)}`)

  let y = 42

  // Medication checklist
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('Medications', 14, y)
  y += 8

  const slots = {}
  data.medications.forEach(med => {
    med.times.forEach(t => {
      if (!slots[t]) slots[t] = []
      slots[t].push(med)
    })
  })

  let totalMeds = 0, givenMeds = 0
  Object.keys(slots).sort().forEach(time => {
    slots[time].forEach(med => {
      totalMeds++
      const key = med.id + '_' + time
      const given = data.medLog[d] && data.medLog[d][key]
      if (given) givenMeds++

      doc.setFontSize(9)
      // Checkbox
      doc.setDrawColor(...COLORS.border)
      doc.rect(16, y - 4, 4, 4)
      if (given) {
        doc.setFillColor(...COLORS.green)
        doc.rect(16, y - 4, 4, 4, 'F')
        doc.setTextColor(...COLORS.white)
        doc.setFontSize(7)
        doc.text('\u2713', 17, y - 0.5)
      }

      doc.setTextColor(...COLORS.text)
      doc.setFontSize(9)
      doc.text(`${formatTime12(time) || ''} - ${med.name || ''} ${med.dose || ''}`, 24, y)
      if (given) {
        doc.setTextColor(...COLORS.green)
        doc.text(`Given at ${formatTime12(given.givenAt) || ''}${given.givenBy ? ' by ' + given.givenBy : ''}`, 120, y)
      } else {
        doc.setTextColor(...COLORS.red)
        doc.text('Not given', 120, y)
      }
      y += 7
    })
  })

  doc.setTextColor(...COLORS.text)
  doc.setFont('helvetica', 'bold')
  doc.text(`${givenMeds}/${totalMeds} medications given`, 14, y + 2)
  y += 14

  // Feeds
  doc.setFontSize(12)
  doc.text('Feeds', 14, y)
  y += 8

  const dayFeeds = data.feeds.filter(f => f.date === d).sort((a, b) => a.time.localeCompare(b.time))
  if (dayFeeds.length === 0) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(...COLORS.muted)
    doc.text('No feeds logged', 14, y)
    y += 8
  } else {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    dayFeeds.forEach(f => {
      doc.setTextColor(...COLORS.text)
      doc.text(`${formatTime12(f.time)} - ${f.type} ${f.amount}mL`, 16, y)
      if (f.notes) {
        doc.setTextColor(...COLORS.muted)
        doc.text(f.notes, 90, y)
      }
      y += 6
    })
    const totalMl = dayFeeds.reduce((s, f) => s + f.amount, 0)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...COLORS.text)
    doc.text(`Total: ${totalMl}mL across ${dayFeeds.length} feeds`, 14, y + 2)
    y += 12
  }

  // Weight
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Latest Weight', 14, y)
  y += 8
  const latestWeight = data.weights.length > 0 ? data.weights[data.weights.length - 1] : null
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  if (latestWeight) {
    doc.text(`${latestWeight.value.toFixed(3)}kg on ${formatDate(latestWeight.date)}`, 14, y)
  } else {
    doc.setTextColor(...COLORS.muted)
    doc.text('No weight recorded', 14, y)
  }
  y += 12

  // Notes
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('Notes', 14, y)
  y += 8

  const dayNotes = (data.notes || []).filter(n => n.date === d)
  if (dayNotes.length === 0) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(...COLORS.muted)
    doc.text('No notes for this day', 14, y)
  } else {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    dayNotes.forEach(n => {
      doc.setTextColor(...COLORS.muted)
      doc.text(`${formatTime12(n.time)}${n.loggedBy ? ' - ' + n.loggedBy : ''}`, 14, y)
      y += 5
      doc.setTextColor(...COLORS.text)
      const lines = doc.splitTextToSize(n.text, 170)
      doc.text(lines, 14, y)
      y += lines.length * 5 + 4
    })
  }

  addFooter(doc, 1)
  doc.save(`daily-summary-${childName.toLowerCase().replace(/\s+/g, '-')}-${d}.pdf`)
}

export function generateWeeklyReport(data, childName) {
  const doc = new jsPDF()
  const endDate = today()
  const startDate = daysAgo(6)
  addHeader(doc, 'Weekly Report', `${childName} - ${formatDate(startDate)} to ${formatDate(endDate)}`)

  let y = 42

  // Med compliance
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('Medication Compliance', 14, y)
  y += 10

  let totalDoses = 0, givenDoses = 0
  for (let i = 6; i >= 0; i--) {
    const d = daysAgo(i)
    data.medications.forEach(med => {
      med.times.forEach(t => {
        totalDoses++
        const key = med.id + '_' + t
        if (data.medLog[d] && data.medLog[d][key]) givenDoses++
      })
    })
  }

  const compliance = totalDoses > 0 ? Math.round((givenDoses / totalDoses) * 100) : 0
  doc.setFontSize(24)
  doc.setTextColor(...(compliance >= 90 ? COLORS.green : compliance >= 70 ? COLORS.primary : COLORS.red))
  doc.text(`${compliance}%`, 14, y + 2)
  doc.setFontSize(9)
  doc.setTextColor(...COLORS.muted)
  doc.text(`${givenDoses} of ${totalDoses} doses given`, 42, y)
  y += 14

  // Daily feed totals
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('Daily Feed Totals', 14, y)
  y += 8

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  for (let i = 6; i >= 0; i--) {
    const d = daysAgo(i)
    const dayFeeds = data.feeds.filter(f => f.date === d)
    const totalMl = dayFeeds.reduce((s, f) => s + f.amount, 0)
    doc.setTextColor(...COLORS.text)
    doc.text(`${formatDate(d)}:`, 16, y)
    doc.text(`${totalMl}mL (${dayFeeds.length} feeds)`, 60, y)
    y += 6
  }
  y += 8

  // Weight trend
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('Weight Trend', 14, y)
  y += 8

  const weekWeights = data.weights.filter(w => w.date >= startDate && w.date <= endDate)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  if (weekWeights.length === 0) {
    doc.setTextColor(...COLORS.muted)
    doc.text('No weights recorded this week', 14, y)
  } else {
    weekWeights.forEach(w => {
      doc.setTextColor(...COLORS.text)
      doc.text(`${formatDate(w.date)}: ${w.value.toFixed(3)}kg`, 16, y)
      y += 6
    })
    if (weekWeights.length >= 2) {
      const first = weekWeights[0].value
      const last = weekWeights[weekWeights.length - 1].value
      const change = last - first
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...(change >= 0 ? COLORS.green : COLORS.red))
      doc.text(`Change: ${change >= 0 ? '+' : ''}${change.toFixed(3)}kg`, 14, y + 2)
    }
  }

  addFooter(doc, 1)
  doc.save(`weekly-report-${childName.toLowerCase().replace(/\s+/g, '-')}-${endDate}.pdf`)
}
